// heroes
export const FETCH_HEROES = 'FETCH_HEROES'
export const FETCH_HERO = 'FETCH_HERO'

// monsters
export const FETCH_MONSTERS = 'FETCH_MONSTERS'
export const FETCH_MONSTER = 'FETCH_MONSTER'

// requests
export const FETCH_REQUESTS = 'FETCH_REQUESTS'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_RECOMMENDED_REQUESTS = 'FETCH_RECOMMENDED_REQUESTS'
export const SET_REQUEST_FILTER = 'SET_REQUEST_FILTER'

// jobs
export const FETCH_JOBS = 'FETCH_JOBS'
export const FETCH_JOBS_BY_HERO = 'FETCH_JOBS_BY_HERO'
export const FETCH_JOBS_BY_STATUS = 'FETCH_JOBS_BY_STATUS'
export const FETCH_JOBS_BY_SEVERITY = 'FETCH_JOBS_BY_SEVERITY'
export const SET_JOB_FILTER = 'SET_JOB_FILTER'

// common
export const SET_ACTIVE_LAYER = 'SET_ACTIVE_LAYER'
export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION'
export const HIDE_ERROR_NOTIFICATION = 'HIDE_ERROR_NOTIFICATION'

// auth
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const SET_USER = 'SET_USER'
