export const FETCH_HEROES = 'FETCH_HEROES'
export const FETCH_MONSTERS = 'FETCH_MONSTERS'
export const FETCH_REQUESTS = 'FETCH_REQUESTS'
export const FETCH_JOBS = 'FETCH_JOBS'

export const FETCH_MONSTER = 'FETCH_MONSTER'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_HERO = 'FETCH_HERO'

export const SET_ACTIVE_LAYER = 'SET_ACTIVE_LAYER'

export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION'
export const HIDE_ERROR_NOTIFICATION = 'HIDE_ERROR_NOTIFICATION'
